version: '2.1'

services:
  fr-backend-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/reform/fr-backend-api
    container_name: fr-backend-api
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
    volumes:
      - ./build/install/fr-backend:/opt/app/
    ports:
      # check .env
      - $SERVER_PORT:$SERVER_PORT
